### ISSUE TITLE
Reloading module does not reload hooks

### ISSUE THREAD

**Issue by Penfold0** [meishuu/tera-proxy#1]
Reloading a module does not seem to reload any of the associated hooks. I can add a new hook, but any deleted or edited hooks seem unaffected.

**Comment by meishuu** [comment]
I think I had the idea to have Dispatch remove the hooks on its own when I was writing it, but I have a feeling that was scrapped because we don't really know which module is adding a hook.

Instead, if the module exports a `destructor` method, it will get called on `unload`, allowing you to remove the hooks yourself.

(Someday, I'll work on adding docs.)

**Comment by Penfold0** [comment]
```
destructor: ->
        @dispatch.unhook 'sSpawnUser'
```

Shows in console:
```
[dispatch] unhook: could not find cb
``` 

I can't seem to remove any hooks. Am I doing something wrong?
