### ISSUE TITLE
Is it possible to use it for KTERA?

### ISSUE THREAD

**Issue by terarian** [meishuu/tera-proxy#8]
I am compeletely new to programming..and I tried to fix sls_url and others with KTERA's adress, but seems it did not work. Is is possible to make it working for KTERA as well as NA tera?

**Comment by alexrp** [comment]
Yes, it's possible, but you need to start the proxy right after you click play in the launcher. This is because KTERA uses the same domain name for logging in and fetching the server list. So if you start the proxy before you log in, the login requests will just go to localhost and be ignored since tera-proxy doesn't currently forward HTTPS traffic.

**Comment by meishuu** [comment]
This *should* be working fine as of v1.0.0. If not, please reopen the issue and provide as many details as you can.
